#define SOL_MIR_PLAN_TEST_HOOKS 1
#include "sol/mir_runtime_handler_abi.h"
#include "sol/package.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures;
static bool reverse_roots;
#define CHECK(x) do { if (!(x)) { fprintf(stderr, "%s:%d: %s\n", __FILE__, __LINE__, #x); ++failures; } } while (0)
typedef struct { SolDiagnostics d; SolHirModule h; SolTypeTable t; SolEffectTable e; SolContractTable k; SolIr ir; SolPackage p; } Fixture;
typedef struct { SolMirConcreteProgram concrete; SolMirRuntimeConventions conventions; SolMirRuntimeValues values; SolMirRuntimeCleanup cleanup; SolMirRuntimeHostAbi host; SolMirRuntimeHandlerAbi abi; } Pipeline;

static SolIrCallableId find(const SolIr *ir,const char*n,SolIrCallableKind k,size_t ordinal) { for(size_t i=0;i<ir->callable_count;i++)if(ir->callables[i].kind==k&&!strcmp(ir->callables[i].name,n)&&!ordinal--)return i;return SOL_IR_NONE; }
static bool setup_at(Fixture*f,const char*path) { memset(f,0,sizeof *f);sol_package_init(&f->p);sol_diagnostics_init(&f->d);sol_hir_module_init(&f->h);sol_type_table_init(&f->t);sol_effect_table_init(&f->e);sol_contract_table_init(&f->k);sol_ir_init(&f->ir);char message[256];if(!sol_package_load_directory(&f->p,path,&f->d,message,sizeof message))return false;SolHirFileScope scopes[3];if(f->p.file_count>3)return false;for(size_t i=0;i<f->p.file_count;i++)scopes[i]=(SolHirFileScope){f->p.files[i].module_name,f->p.files[i].import_start,f->p.files[i].import_count,f->p.files[i].item_start,f->p.files[i].item_count};return sol_hir_lower_scoped(&f->p.source,&f->p.syntax,scopes,f->p.file_count,&f->h,&f->d)&&sol_type_check(&f->p.source,&f->p.syntax,&f->h,&f->t,&f->d)&&sol_effect_check(&f->p.source,&f->p.syntax,&f->h,&f->t,&f->e,&f->d)&&sol_contract_lower(&f->p.source,&f->p.syntax,&f->h,&f->t,&f->e,&f->k,&f->d)&&sol_ir_lower_scoped(&f->p.source,&f->p.syntax,&f->h,&f->t,&f->e,&f->k,f->p.files,f->p.file_count,&f->ir,&f->d); }
static bool setup(Fixture*f) { return setup_at(f,SOL_TEST_SOURCE_DIR "/tests/conformance/p35"); }
static void finish(Fixture*f) { sol_ir_free(&f->ir);sol_contract_table_free(&f->k);sol_effect_table_free(&f->e);sol_type_table_free(&f->t);sol_hir_module_free(&f->h);sol_diagnostics_free(&f->d);sol_package_free(&f->p); }
static void pipeline_init(Pipeline*p) { memset(p,0,sizeof *p);sol_mir_concrete_program_init(&p->concrete);sol_mir_runtime_conventions_init(&p->conventions);sol_mir_runtime_values_init(&p->values);sol_mir_runtime_cleanup_init(&p->cleanup);sol_mir_runtime_host_abi_init(&p->host);sol_mir_runtime_handler_abi_init(&p->abi); }
static void pipeline_free(Pipeline*p) { sol_mir_runtime_handler_abi_free(&p->abi);sol_mir_runtime_host_abi_free(&p->host);sol_mir_runtime_cleanup_free(&p->cleanup);sol_mir_runtime_values_free(&p->values);sol_mir_runtime_conventions_free(&p->conventions);sol_mir_concrete_program_free(&p->concrete); }
static bool build_roots(Fixture*f,Pipeline*p,const SolMirRuntimeHandlerAbiLimits*limits,size_t root_count) {
    SolMirProgramRoot roots[]={
        {find(&f->ir,"newest",SOL_IR_CALLABLE_FUNCTION,0),SOL_MIR_PROGRAM_ROOT_INTERNAL_FIXTURE},
        {find(&f->ir,"distinct_roots",SOL_IR_CALLABLE_FUNCTION,0),SOL_MIR_PROGRAM_ROOT_INTERNAL_FIXTURE},
        {find(&f->ir,"one_handler",SOL_IR_CALLABLE_FUNCTION,0),SOL_MIR_PROGRAM_ROOT_INTERNAL_FIXTURE},
        {find(&f->ir,"cleanup_return",SOL_IR_CALLABLE_FUNCTION,0),SOL_MIR_PROGRAM_ROOT_INTERNAL_FIXTURE},
        {find(&f->ir,"cleanup_failure",SOL_IR_CALLABLE_FUNCTION,0),SOL_MIR_PROGRAM_ROOT_INTERNAL_FIXTURE},
    };
    if(reverse_roots)for(size_t i=0;i<sizeof roots/sizeof *roots/2;i++){SolMirProgramRoot swap=roots[i];roots[i]=roots[sizeof roots/sizeof *roots-1-i];roots[sizeof roots/sizeof *roots-1-i]=swap;}
    SolIrCallableId imports[]={find(&f->ir,"write",SOL_IR_CALLABLE_CAPABILITY,0)};
    SolMirTargetDescriptor target=sol_mir_target_wasm32();
    return root_count&&root_count<=sizeof roots/sizeof *roots&&roots[0].callable!=SOL_IR_NONE&&roots[1].callable!=SOL_IR_NONE&&roots[2].callable!=SOL_IR_NONE&&roots[3].callable!=SOL_IR_NONE&&roots[4].callable!=SOL_IR_NONE&&imports[0]!=SOL_IR_NONE&&sol_mir_concrete_program_build(&(SolMirConcreteBuildRequest){&f->ir,roots,root_count,imports,1,&target,NULL},&p->concrete,&f->d)==SOL_MIR_CONCRETE_BUILD_SUCCEEDED&&sol_mir_runtime_conventions_build(&(SolMirRuntimeConventionsBuildRequest){&p->concrete,NULL},&p->conventions,&f->d)==SOL_MIR_RUNTIME_CONVENTIONS_BUILD_SUCCEEDED&&sol_mir_runtime_values_build(&(SolMirRuntimeValuesBuildRequest){&p->conventions,NULL},&p->values,&f->d)==SOL_MIR_RUNTIME_VALUES_BUILD_SUCCEEDED&&sol_mir_runtime_cleanup_build(&(SolMirRuntimeCleanupBuildRequest){&p->conventions,&p->values,NULL},&p->cleanup,&f->d)==SOL_MIR_RUNTIME_CLEANUP_BUILD_SUCCEEDED&&sol_mir_runtime_host_abi_build(&(SolMirRuntimeHostAbiBuildRequest){&p->conventions,&p->values,&p->cleanup,NULL},&p->host,&f->d)==SOL_MIR_RUNTIME_HOST_ABI_BUILD_SUCCEEDED&&sol_mir_runtime_handler_abi_build(&(SolMirRuntimeHandlerAbiBuildRequest){&p->conventions,&p->values,&p->cleanup,&p->host,limits},&p->abi,&f->d)==SOL_MIR_RUNTIME_HANDLER_ABI_BUILD_SUCCEEDED;
}
static bool build(Fixture*f,Pipeline*p,const SolMirRuntimeHandlerAbiLimits*limits) { return build_roots(f,p,limits,5); }
static bool bytes(const SolMirRuntimeHandlerAbi*a,unsigned char **out,size_t *length) { *out=NULL;*length=0;FILE*s=tmpfile();if(!s||!sol_mir_runtime_handler_abi_render(s,a)||fflush(s)||fseek(s,0,SEEK_END))goto done;long n=ftell(s);if(n<0||(uintmax_t)n>SIZE_MAX||fseek(s,0,SEEK_SET))goto done;*out=malloc((size_t)n+1);if(!*out)goto done;*length=(size_t)n;if(fread(*out,1,*length,s)!=*length){free(*out);*out=NULL;*length=0;}else (*out)[*length]=0;done:if(s)fclose(s);return *out!=NULL; }
static void reject_render(SolMirRuntimeHandlerAbi*a) { FILE*s=tmpfile();CHECK(s!=NULL);if(!s)return;CHECK(!sol_mir_runtime_handler_abi_render(s,a));CHECK(fseek(s,0,SEEK_END)==0&&ftell(s)==0);fclose(s); }
static SolMirRuntimeHandlerDispatch dispatch(const SolMirRuntimeHandlerFramePlan*f,uint64_t root) { return (SolMirRuntimeHandlerDispatch){f->source_binding,f->source_operation,f->source_signature,root}; }
static size_t root_frame(const SolMirRuntimeHandlerAbi*a,size_t nth) { for(size_t i=0;i<a->frame_count;i++)if(a->frames[i].parent==SOL_MIR_RUNTIME_NONE&&!nth--)return i;return SOL_MIR_RUNTIME_NONE; }
static size_t child_frame(const SolMirRuntimeHandlerAbi*a,size_t parent) { for(size_t i=0;i<a->frame_count;i++)if(a->frames[i].parent==parent)return i;return SOL_MIR_RUNTIME_NONE; }
static bool enter_path(const SolMirRuntimeHandlerAbi*a,SolMirRuntimeHandlerActivationStack*s,size_t frame,uint64_t root) { size_t path[32],n=0;while(frame!=SOL_MIR_RUNTIME_NONE&&n<sizeof path/sizeof path[0]){path[n++]=frame;frame=a->frames[frame].parent;}if(frame!=SOL_MIR_RUNTIME_NONE)return false;while(n)if(!sol_mir_runtime_handler_abi_test_enter(a,s,path[--n],root,true))return false;return true; }
static bool same_stack(const SolMirRuntimeHandlerActivationStack*a,const SolMirRuntimeHandlerActivationStack*b,const SolMirRuntimeHandlerActivation*frames,const SolMirRuntimeHandlerActivation*saved) { return !memcmp(a,b,sizeof *a)&&!memcmp(frames,saved,b->count*sizeof *frames); }

static void test_activation(const SolMirRuntimeHandlerAbi*a) {
    size_t outer=root_frame(a,0),inner=child_frame(a,outer);CHECK(outer!=SOL_MIR_RUNTIME_NONE&&inner!=SOL_MIR_RUNTIME_NONE);if(outer==SOL_MIR_RUNTIME_NONE||inner==SOL_MIR_RUNTIME_NONE)return;
    SolMirRuntimeHandlerActivation storage[16];SolMirRuntimeHandlerActivationStack stack;sol_mir_runtime_handler_abi_test_stack_init(&stack,storage,16);
    CHECK(!sol_mir_runtime_handler_abi_test_enter(a,&stack,outer,1,false)&&stack.count==0);
    CHECK(enter_path(a,&stack,inner,1)&&stack.count==2&&stack.frames[1].parent==outer);
    SolMirRuntimeHandlerSelection pick;SolMirRuntimeHandlerDispatch d=dispatch(&a->frames[inner],1);
    /* All caller-owned storage, including visibility and every activation
       coordinate, is sealed before an operation can inspect it. */
    SolMirRuntimeHandlerActivationStack good=stack,forged=stack;forged.visible_count=0;CHECK(sol_mir_runtime_handler_abi_test_select(a,&forged,&d,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_INVALID&&!memcmp(&forged,&(SolMirRuntimeHandlerActivationStack){.frames=storage,.count=2,.capacity=16,.visible_count=0,.seal=good.seal},sizeof forged));SolMirRuntimeHandlerActivation bad_storage[16];memcpy(bad_storage,storage,sizeof storage);forged=good;forged.frames=bad_storage;forged.frames[1].root=9;CHECK(sol_mir_runtime_handler_abi_test_select(a,&forged,&d,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_INVALID&&forged.frames[1].root==9);
    CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&d,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_MATCH&&pick.frame==inner&&pick.active_index==1&&pick.hidden_count==1);
    CHECK(sol_mir_runtime_handler_abi_test_hide(a,&stack,&pick)&&stack.visible_count==1&&pick.hidden_count==1);
    /* An older exact frame can be selected and hidden while the inner suffix
       remains physically present but hidden.  Each selection restores only
       the visible prefix it sealed before its own hide. */
    SolMirRuntimeHandlerSelection older;
    CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&d,&older)==SOL_MIR_RUNTIME_HANDLER_SELECT_MATCH&&older.frame==outer&&older.active_index==0&&older.hidden_count==1);
    CHECK(sol_mir_runtime_handler_abi_test_hide(a,&stack,&older)&&stack.visible_count==0&&older.hidden_count==1);
    SolMirRuntimeHandlerSelection no_match;
    CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&d,&no_match)==SOL_MIR_RUNTIME_HANDLER_SELECT_NO_MATCH);
#define CHECK_REJECT_STACK(call) do { SolMirRuntimeHandlerActivationStack before=stack;SolMirRuntimeHandlerActivation saved[16];memcpy(saved,storage,before.count*sizeof *saved);CHECK(!(call)&&same_stack(&stack,&before,storage,saved)); } while(0)
    /* The inner transaction is blocked by the nested older transaction; an
       active selection cannot be hidden twice, and altered selections cannot
       authenticate the current hidden state. */
    CHECK_REJECT_STACK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&pick,true));
    CHECK_REJECT_STACK(sol_mir_runtime_handler_abi_test_hide(a,&stack,&older));
    SolMirRuntimeHandlerSelection forged_selection=older;forged_selection.hidden_count++;
    CHECK_REJECT_STACK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&forged_selection,true));
    SolMirRuntimeHandlerSelection swapped=older;swapped.active_index=pick.active_index;swapped.frame=pick.frame;
    CHECK_REJECT_STACK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&swapped,true));
    CHECK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&older,true)&&stack.visible_count==1&&stack.count==2);
    CHECK_REJECT_STACK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&older,true));
    CHECK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&pick,true)&&stack.visible_count==stack.count);
    CHECK_REJECT_STACK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&pick,true));

    /* Provider failure restores the older prefix exactly as success does; the
       original inner selection then restores full visibility. */
    sol_mir_runtime_handler_abi_test_stack_init(&stack,storage,16);CHECK(enter_path(a,&stack,inner,1));
    CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&d,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_MATCH&&sol_mir_runtime_handler_abi_test_hide(a,&stack,&pick));
    CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&d,&older)==SOL_MIR_RUNTIME_HANDLER_SELECT_MATCH&&sol_mir_runtime_handler_abi_test_hide(a,&stack,&older));
    CHECK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&older,false)&&stack.visible_count==1);
    CHECK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&pick,false)&&stack.visible_count==stack.count);

    /* Mutating either hidden suffix invalidates its sealed transaction and
       must not cause restore to change caller-owned stack storage. */
    sol_mir_runtime_handler_abi_test_stack_init(&stack,storage,16);CHECK(enter_path(a,&stack,inner,1));
    CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&d,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_MATCH&&sol_mir_runtime_handler_abi_test_hide(a,&stack,&pick));
    CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&d,&older)==SOL_MIR_RUNTIME_HANDLER_SELECT_MATCH&&sol_mir_runtime_handler_abi_test_hide(a,&stack,&older));
    storage[1].root^=UINT64_C(1);
    CHECK_REJECT_STACK(sol_mir_runtime_handler_abi_test_restore(a,&stack,&older,true));
#undef CHECK_REJECT_STACK
    sol_mir_runtime_handler_abi_test_stack_init(&stack,storage,16);CHECK(enter_path(a,&stack,inner,1));
    SolMirRuntimeHandlerDispatch wrong=d;wrong.root=2;CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&wrong,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_NO_MATCH);wrong=d;wrong.operation.root^=1;CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&wrong,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_MATCH);wrong=d;wrong.operation.effects^=1;CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&wrong,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_NO_MATCH);wrong=d;wrong.source_binding^=1;CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&wrong,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_MATCH);wrong=d;wrong.signature^=1;CHECK(sol_mir_runtime_handler_abi_test_select(a,&stack,&wrong,&pick)==SOL_MIR_RUNTIME_HANDLER_SELECT_NO_MATCH);
    size_t count=stack.count;CHECK(!sol_mir_runtime_handler_abi_test_exit_marker(a,&stack,outer,a->exit_markers[a->frames[outer].exit_markers.offset].instruction)&&stack.count==count);
    CHECK(sol_mir_runtime_handler_abi_test_exit_marker(a,&stack,inner,a->exit_markers[a->frames[inner].exit_markers.offset].instruction)&&stack.count==1);
    CHECK(!sol_mir_runtime_handler_abi_test_exit_marker(a,&stack,inner,a->exit_markers[a->frames[inner].exit_markers.offset].instruction)&&stack.count==1);
    CHECK(sol_mir_runtime_handler_abi_test_exit_marker(a,&stack,outer,a->exit_markers[a->frames[outer].exit_markers.offset].instruction)&&stack.count==0);
    CHECK(enter_path(a,&stack,outer,1)&&sol_mir_runtime_handler_abi_test_exit_marker(a,&stack,outer,a->exit_markers[a->frames[outer].exit_markers.offset].instruction));
    CHECK(enter_path(a,&stack,outer,1)&&sol_mir_runtime_handler_abi_test_exit_marker(a,&stack,outer,a->exit_markers[a->frames[outer].exit_markers.offset].instruction));
}
static void test_exits(const SolMirRuntimeHandlerAbi*a) { for(size_t i=0;i<a->frame_count;i++){if(a->frames[i].parent!=SOL_MIR_RUNTIME_NONE)continue;SolMirRuntimeHandlerActivation storage[16];SolMirRuntimeHandlerActivationStack s;sol_mir_runtime_handler_abi_test_stack_init(&s,storage,16);CHECK(enter_path(a,&s,i,1));size_t marker=a->exit_markers[a->frames[i].exit_markers.offset].instruction;CHECK(sol_mir_runtime_handler_abi_test_exit_marker(a,&s,i,marker)&&s.count==0);for(size_t q=0;q<a->frames[i].cleanup_exits.count;q++){sol_mir_runtime_handler_abi_test_stack_init(&s,storage,16);CHECK(enter_path(a,&s,i,1));size_t action=a->cleanup_exits[a->frames[i].cleanup_exits.offset+q].action;CHECK(sol_mir_runtime_handler_abi_test_exit_cleanup(a,&s,i,action)&&s.count==0);CHECK(!sol_mir_runtime_handler_abi_test_exit_cleanup(a,&s,i,action));}}
}
static bool equal_usage(const SolMirRuntimeHandlerAbiUsage*a,const SolMirRuntimeHandlerAbiUsage*b) { return a->frames==b->frames&&a->marker_references==b->marker_references&&a->cleanup_exits==b->cleanup_exits&&a->stack_depth==b->stack_depth&&a->test_work==b->test_work&&a->owned_bytes==b->owned_bytes&&a->build_scratch_bytes==b->build_scratch_bytes&&a->build_work==b->build_work&&a->validation_scratch_bytes==b->validation_scratch_bytes&&a->validation_work==b->validation_work; }
static void test_build_work_symmetry(Fixture*f,const Pipeline*p) { size_t predicted=0;CHECK(sol_mir_runtime_handler_abi_test_predict_build_work(&p->conventions,&p->cleanup,&predicted)&&predicted==p->abi.usage.build_work&&sol_mir_runtime_handler_abi_validate(&p->abi,NULL));Pipeline narrow;pipeline_init(&narrow);CHECK(build_roots(f,&narrow,NULL,1));size_t narrow_predicted=0;CHECK(sol_mir_runtime_handler_abi_test_predict_build_work(&narrow.conventions,&narrow.cleanup,&narrow_predicted)&&narrow_predicted==narrow.abi.usage.build_work&&sol_mir_runtime_handler_abi_validate(&narrow.abi,NULL));CHECK(p->concrete.linkage.binding_count!=narrow.concrete.linkage.binding_count&&p->conventions.signature_count!=narrow.conventions.signature_count);pipeline_free(&narrow); }
static void test_limits(Fixture*f,const Pipeline*p) { SolMirRuntimeHandlerAbiLimits exact=p->abi.limits;exact.max_frames=p->abi.usage.frames;exact.max_marker_references=p->abi.usage.marker_references;exact.max_cleanup_exits=p->abi.usage.cleanup_exits?p->abi.usage.cleanup_exits:1;exact.max_stack_depth=p->abi.usage.stack_depth;exact.max_test_work=p->abi.usage.test_work;exact.max_owned_bytes=p->abi.usage.owned_bytes;exact.max_build_scratch_bytes=p->abi.usage.build_scratch_bytes;exact.max_build_work=p->abi.usage.build_work;exact.max_validation_scratch_bytes=p->abi.usage.validation_scratch_bytes;exact.max_validation_work=p->abi.usage.validation_work;size_t *all[]={&exact.max_frames,&exact.max_marker_references,&exact.max_cleanup_exits,&exact.max_stack_depth,&exact.max_test_work,&exact.max_owned_bytes,&exact.max_build_scratch_bytes,&exact.max_build_work,&exact.max_validation_scratch_bytes,&exact.max_validation_work};for(size_t i=0;i<sizeof all/sizeof *all;i++){if(!*all[i]||(all[i]==&exact.max_cleanup_exits&&!p->abi.usage.cleanup_exits))continue;Pipeline b;pipeline_init(&b);CHECK(build(f,&b,&exact));pipeline_free(&b);--*all[i];pipeline_init(&b);CHECK(!build(f,&b,&exact)&&b.abi.frame_count==0&&b.abi.frames==NULL);pipeline_free(&b);++*all[i];}
    Pipeline b;pipeline_init(&b);sol_mir_runtime_handler_abi_test_force_build_scratch_allocation_failure(true);CHECK(!build(f,&b,&exact)&&b.abi.frames==NULL);sol_mir_runtime_handler_abi_test_force_build_scratch_allocation_failure(false);sol_mir_runtime_handler_abi_test_force_persistent_allocation_failure(true);CHECK(!build(f,&b,&exact)&&b.abi.frames==NULL);sol_mir_runtime_handler_abi_test_force_persistent_allocation_failure(false);sol_mir_runtime_handler_abi_test_force_validation_scratch_failure(true);CHECK(!build(f,&b,&exact)&&b.abi.frames==NULL);sol_mir_runtime_handler_abi_test_force_validation_scratch_failure(false);pipeline_free(&b);
}
static void test_mutations(Pipeline*p) { SolMirRuntimeHandlerAbi*a=&p->abi;CHECK(a->frame_count&&a->exit_marker_count);if(!a->frame_count)return;unsigned char *render=NULL;size_t size=0;CHECK(bytes(a,&render,&size));unsigned char *again=NULL;size_t again_size=0;CHECK(bytes(a,&again,&again_size)&&size==again_size&&!memcmp(render,again,size));free(render);free(again);size_t saved_validation_work=a->usage.validation_work;a->usage.validation_work=0;CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));a->usage.validation_work=saved_validation_work;CHECK(sol_mir_runtime_handler_abi_validate(a,NULL));SolMirRuntimeHandlerAbiLimits saved_limits=a->limits;a->limits.max_validation_work=a->usage.validation_work;CHECK(sol_mir_runtime_handler_abi_validate(a,NULL));--a->limits.max_validation_work;CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));a->limits=saved_limits;CHECK(sol_mir_runtime_handler_abi_validate(a,NULL));uint64_t authentication=a->authentication;a->authentication^=UINT64_C(1);CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));a->authentication=authentication;CHECK(sol_mir_runtime_handler_abi_validate(a,NULL));
#define MUTATE(field) do { size_t saved=(size_t)a->frames[0].field;a->frames[0].field=(size_t)(saved+1);CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));reject_render(a);a->frames[0].field=saved;CHECK(sol_mir_runtime_handler_abi_validate(a,NULL)); } while(0)
    MUTATE(handler);MUTATE(source_binding);MUTATE(source_signature);MUTATE(root_match);MUTATE(authority_root);MUTATE(effects);MUTATE(provider_binding);MUTATE(provider_place);MUTATE(provider_recipe);MUTATE(provider_access);MUTATE(provider_internal);MUTATE(provider_signature);MUTATE(enter_marker);MUTATE(parent);
#undef MUTATE
    SolMirRuntimeHandlerExitMarker marker=a->exit_markers[0];a->exit_markers[0].instruction++;CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));a->exit_markers[0]=marker;if(a->cleanup_exit_count){SolMirRuntimeHandlerCleanupExit cleanup=a->cleanup_exits[0];a->cleanup_exits[0].action++;CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));a->cleanup_exits[0]=cleanup;}CHECK(sol_mir_runtime_handler_abi_validate(a,NULL));
    SolMirRuntimeHandlerFramePlan *frames=a->frames;a->frames=(SolMirRuntimeHandlerFramePlan *)(void *)a->exit_markers;CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));reject_render(a);a->frames=frames;SolMirRuntimeHandlerExitMarker *markers=a->exit_markers;a->exit_markers=(SolMirRuntimeHandlerExitMarker *)(void *)a->cleanup_exits;CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));reject_render(a);a->exit_markers=markers;SolMirRuntimeHandlerCleanupExit *exits=a->cleanup_exits;const void *aliases[]={p->conventions.imports,p->concrete.program.roots,p->concrete.plan.types,p->concrete.materialization.locals,p->concrete.representation.recipes,p->concrete.layout.types,p->concrete.operations.handlers,p->concrete.linkage.bindings,p->concrete.program.templates[0].mir.instructions,p->concrete.materialization.images[0].topology.blocks,p->concrete.program.ir->source_bytes,p->concrete.program.ir->source_bytes+1,p->concrete.program.ir->definitions[0].name+1,p->values.ownership_plans,p->cleanup.transitions,p->host.operations};for(size_t i=0;i<sizeof aliases/sizeof *aliases;i++){a->cleanup_exits=(SolMirRuntimeHandlerCleanupExit *)(void *)aliases[i];CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));reject_render(a);}a->cleanup_exits=exits;CHECK(sol_mir_runtime_handler_abi_validate(a,NULL));
    SolMirInstruction *saved_template_instructions=p->concrete.program.templates[0].mir.instructions;p->concrete.program.templates[0].mir.instructions=NULL;CHECK(!sol_mir_runtime_handler_abi_validate(a,NULL));reject_render(a);p->concrete.program.templates[0].mir.instructions=saved_template_instructions;CHECK(sol_mir_runtime_handler_abi_validate(a,NULL));
}
static void allocate_noise(void**live,size_t count,size_t seed) { for(size_t i=0;i<count;i++){size_t bytes=(seed+1)*(i+17)*97%8191+1;live[i]=malloc(bytes);CHECK(live[i]!=NULL);}for(size_t i=1;i<count;i+=2){free(live[i]);live[i]=NULL;} }
static void free_noise(void**live,size_t count) { for(size_t i=0;i<count;i++){free(live[i]);live[i]=NULL;} }
static void test_build_determinism(const SolMirRuntimeHandlerAbi *baseline) { static const struct { const char *path; bool roots; } cases[]={{SOL_TEST_SOURCE_DIR "/tests/conformance/p35",false},{SOL_TEST_SOURCE_DIR "/tests/conformance/p35",true},{SOL_TEST_SOURCE_DIR "/tests/conformance/p35_reordered",false},{SOL_TEST_SOURCE_DIR "/tests/conformance/p35_reordered",true}};unsigned char *expected=NULL;size_t expected_n=0;CHECK(bytes(baseline,&expected,&expected_n));for(size_t i=0;i<sizeof cases/sizeof *cases;i++){Fixture f;Pipeline first,second;void*live[11]={0};unsigned char *left=NULL,*right=NULL;size_t left_n=0,right_n=0;pipeline_init(&first);pipeline_init(&second);bool ready=setup_at(&f,cases[i].path);CHECK(ready);reverse_roots=cases[i].roots;allocate_noise(live,sizeof live/sizeof *live,i*31+7);bool one=ready&&build(&f,&first,NULL);free_noise(live,sizeof live/sizeof *live);allocate_noise(live,sizeof live/sizeof *live,i*47+13);bool two=ready&&build(&f,&second,NULL);free_noise(live,sizeof live/sizeof *live);CHECK(one&&two);if(one&&two){CHECK(equal_usage(&first.abi.usage,&second.abi.usage));CHECK(bytes(&first.abi,&left,&left_n)&&bytes(&second.abi,&right,&right_n)&&left_n==right_n&&!memcmp(left,right,left_n));CHECK(expected&&left&&expected_n==left_n&&!memcmp(expected,left,expected_n));}free(left);free(right);pipeline_free(&second);pipeline_free(&first);finish(&f);}reverse_roots=false;free(expected); }
static void test_e6_zero_owner(void) { Fixture f;Pipeline p;pipeline_init(&p);if(!setup_at(&f,SOL_TEST_SOURCE_DIR "/tests/conformance/e6")){CHECK(false);pipeline_free(&p);return;}SolMirProgramRoot root={find(&f.ir,"launch",SOL_IR_CALLABLE_FUNCTION,0),SOL_MIR_PROGRAM_ROOT_ENTRY};const char*names[]={"write","get","count","read"};SolIrCallableId imports[4];for(size_t i=0;i<4;i++)imports[i]=find(&f.ir,names[i],SOL_IR_CALLABLE_CAPABILITY,0);SolMirTargetDescriptor target=sol_mir_target_wasm32();CHECK(root.callable!=SOL_IR_NONE&&sol_mir_concrete_program_build(&(SolMirConcreteBuildRequest){&f.ir,&root,1,imports,4,&target,NULL},&p.concrete,&f.d)==SOL_MIR_CONCRETE_BUILD_SUCCEEDED&&sol_mir_runtime_conventions_build(&(SolMirRuntimeConventionsBuildRequest){&p.concrete,NULL},&p.conventions,&f.d)==SOL_MIR_RUNTIME_CONVENTIONS_BUILD_SUCCEEDED&&sol_mir_runtime_values_build(&(SolMirRuntimeValuesBuildRequest){&p.conventions,NULL},&p.values,&f.d)==SOL_MIR_RUNTIME_VALUES_BUILD_SUCCEEDED&&sol_mir_runtime_cleanup_build(&(SolMirRuntimeCleanupBuildRequest){&p.conventions,&p.values,NULL},&p.cleanup,&f.d)==SOL_MIR_RUNTIME_CLEANUP_BUILD_SUCCEEDED&&sol_mir_runtime_host_abi_build(&(SolMirRuntimeHostAbiBuildRequest){&p.conventions,&p.values,&p.cleanup,NULL},&p.host,&f.d)==SOL_MIR_RUNTIME_HOST_ABI_BUILD_SUCCEEDED&&sol_mir_runtime_handler_abi_build(&(SolMirRuntimeHandlerAbiBuildRequest){&p.conventions,&p.values,&p.cleanup,&p.host,NULL},&p.abi,&f.d)==SOL_MIR_RUNTIME_HANDLER_ABI_BUILD_SUCCEEDED);CHECK(!p.abi.frame_count&&!p.abi.exit_marker_count&&!p.abi.cleanup_exit_count&&!p.abi.usage.frames&&!p.abi.usage.marker_references&&!p.abi.usage.cleanup_exits&&!p.abi.usage.stack_depth&&!p.abi.usage.test_work&&!p.abi.usage.owned_bytes&&!p.abi.usage.build_scratch_bytes&&p.abi.usage.build_work==22&&!p.abi.usage.validation_scratch_bytes&&p.abi.usage.validation_work==6462);CHECK(sol_mir_runtime_handler_abi_validate(&p.abi,NULL));unsigned char *first=NULL,*second=NULL;size_t first_n=0,second_n=0;CHECK(bytes(&p.abi,&first,&first_n)&&bytes(&p.abi,&second,&second_n)&&first_n==second_n&&!memcmp(first,second,first_n));CHECK(first_n==61&&!memcmp(first,"runtime-handler-abi handler-abi=true handler-execution=false\n",first_n));free(first);free(second);uint64_t authentication=p.abi.authentication;p.abi.authentication=0;reject_render(&p.abi);p.abi.authentication=authentication;CHECK(sol_mir_runtime_handler_abi_validate(&p.abi,NULL));pipeline_free(&p);finish(&f); }
int main(void) { test_e6_zero_owner();test_e6_zero_owner();Fixture f;CHECK(setup(&f));if(failures){finish(&f);return 1;}Pipeline p;pipeline_init(&p);if(!build(&f,&p,NULL)){CHECK(false);sol_diagnostics_render_human(stderr,&f.p.source,&f.d);pipeline_free(&p);finish(&f);return 1;}CHECK(p.abi.frame_count==7&&p.abi.exit_marker_count==14&&p.abi.cleanup_exit_count==15);CHECK(p.abi.usage.owned_bytes==2320&&p.abi.usage.build_scratch_bytes==56&&p.abi.usage.build_work==9604&&p.abi.usage.validation_scratch_bytes==56&&p.abi.usage.validation_work==17913);CHECK(sol_mir_runtime_handler_abi_validate(&p.abi,NULL));test_activation(&p.abi);test_exits(&p.abi);test_mutations(&p);test_limits(&f,&p);test_build_work_symmetry(&f,&p);test_build_determinism(&p.abi);pipeline_free(&p);finish(&f);return failures?1:0; }
