#include "sol/mir_runtime_handler_abi.h"
#include "mir_runtime_handler_abi_internal.h"
#include "mir_runtime_arena_internal.h"

#include <stdlib.h>
#include <string.h>

static bool bad(SolDiagnostics*d,const char*m) { if(d)sol_diagnostics_add(d,"SOL-MIR-RUNTIME-HANDLER-ABI-002",SOL_SEVERITY_ERROR,(SolSpan){0},m);return false; }
static bool add(size_t*a,size_t b) { if(b>SIZE_MAX-*a)return false;*a+=b;return true; }
static bool mul(size_t a,size_t b,size_t*r) { if(a&&b>SIZE_MAX/a)return false;*r=a*b;return true; }
static bool tick(SolMirRuntimeHandlerAbiWorkMeter*m) { return sol_mir_runtime_handler_abi_tick(m); }
static bool range(const void*p,size_t n,size_t z,SolMirRuntimeHandlerAbiWorkMeter*m) { size_t b;if(!n)return tick(m)&&p==NULL;return tick(m)&&p&&tick(m)&&mul(n,z,&b)&&tick(m)&&(uintptr_t)p<=UINTPTR_MAX-b; }
static bool overlap(const void*a,size_t an,size_t az,const void*b,size_t bn,size_t bz,SolMirRuntimeHandlerAbiWorkMeter*m) { size_t ab,bb;bool left,right;if(!tick(m)||!an||!bn)return false;if(!tick(m)||!mul(an,az,&ab)||!tick(m)||!mul(bn,bz,&bb))return false;if(!tick(m))return false;left=(uintptr_t)a<(uintptr_t)b+bb;if(!tick(m))return false;right=(uintptr_t)b<(uintptr_t)a+ab;return left&&right; }
static bool aliases(const SolMirRuntimeHandlerAbi*o,const void*p,size_t n,size_t z,SolMirRuntimeHandlerAbiWorkMeter*m) { return overlap(o->frames,o->frame_count,sizeof(*o->frames),p,n,z,m)||overlap(o->exit_markers,o->exit_marker_count,sizeof(*o->exit_markers),p,n,z,m)||overlap(o->cleanup_exits,o->cleanup_exit_count,sizeof(*o->cleanup_exits),p,n,z,m); }

typedef struct { const SolMirRuntimeHandlerAbi *owner; SolMirRuntimeHandlerAbiWorkMeter *meter; } HandlerAliasContext;
static SolMirRuntimeTextGuardResult handler_text_guard(uintptr_t address,uintptr_t *boundary,void *opaque) { HandlerAliasContext*x=opaque;const void*p[]={x->owner->frames,x->owner->exit_markers,x->owner->cleanup_exits};size_t n[]={x->owner->frame_count,x->owner->exit_marker_count,x->owner->cleanup_exit_count},z[]={sizeof(*x->owner->frames),sizeof(*x->owner->exit_markers),sizeof(*x->owner->cleanup_exits)};uintptr_t next=UINTPTR_MAX;bool hit=false;for(size_t i=0;i<3;i++){size_t bytes;if(!tick(x->meter)||!mul(n[i],z[i],&bytes))return SOL_MIR_RUNTIME_TEXT_EXHAUSTED;if(!n[i])continue;uintptr_t start=(uintptr_t)p[i],end=start+bytes;hit|=address>=start&&address<end;if(start>address&&start<next)next=start;}if(hit)return SOL_MIR_RUNTIME_TEXT_OVERLAP;*boundary=next;return SOL_MIR_RUNTIME_TEXT_SAFE;}
static bool visit_handler_alias(const void *pointer,size_t count,size_t size,void *context) {
    HandlerAliasContext *x=context;
    if(pointer==NULL&&count==0&&size==0)return tick(x->meter);
    return tick(x->meter) && !aliases(x->owner,pointer,count,size,x->meter);
}
/* The shared raw census includes all nested P2 MIR and IR text arenas. */
static bool aliases_transitive(const SolMirRuntimeHandlerAbi*o,SolMirRuntimeHandlerAbiWorkMeter*m) {
    HandlerAliasContext context={o,m};
    SolMirRuntimeTextGuard saved_guard=sol_mir_runtime_text_guard;void *saved_context=sol_mir_runtime_text_guard_context;
    sol_mir_runtime_text_guard=handler_text_guard;sol_mir_runtime_text_guard_context=&context;
    SolMirRuntimeArenaVisit result=sol_mir_runtime_visit_concrete_arenas(o->conventions->concrete,visit_handler_alias,&context);
    sol_mir_runtime_text_guard=saved_guard;sol_mir_runtime_text_guard_context=saved_context;
    return result != SOL_MIR_RUNTIME_ARENA_VISIT_OK;
}
static bool aliases_predecessor(const SolMirRuntimeHandlerAbi*o,SolMirRuntimeHandlerAbiWorkMeter*m) {
#define CONVENTION_ARENA(member,type,singular) do { if(!tick(m))return false; if(aliases(o,o->conventions->member,o->conventions->singular##_count,sizeof(type),m))return true; } while(0);
    SOL_MIR_RUNTIME_CONVENTIONS_ARENAS(CONVENTION_ARENA)
#undef CONVENTION_ARENA
#define VALUE_ARENA(member,count,type) do { if(!tick(m))return false; if(aliases(o,o->values->member,o->values->count,sizeof(type),m))return true; } while(0)
    VALUE_ARENA(recipe_operations,recipe_operation_count,SolMirRuntimeRecipeOperations);VALUE_ARENA(allocation_plans,allocation_plan_count,SolMirRuntimeAllocationPlan);VALUE_ARENA(copy_plans,copy_plan_count,SolMirRuntimeCopyPlan);VALUE_ARENA(equality_plans,equality_plan_count,SolMirRuntimeEqualityPlan);VALUE_ARENA(host_result_plans,host_result_plan_count,SolMirRuntimeHostResultPlan);VALUE_ARENA(host_result_requirements,host_result_requirement_count,SolMirRuntimeHostResultRequirement);VALUE_ARENA(ownership_plans,ownership_plan_count,SolMirRuntimeOwnershipPlan);VALUE_ARENA(ownership_variants,ownership_variant_count,SolMirRuntimeOwnershipVariant);VALUE_ARENA(owned_edges,owned_edge_count,SolMirRuntimeOwnedEdge);
#undef VALUE_ARENA
#define CLEANUP_ARENA(member,count,type) do { if(!tick(m))return false; if(aliases(o,o->cleanup->member,o->cleanup->count,sizeof(type),m))return true; } while(0)
    CLEANUP_ARENA(events,event_count,SolMirRuntimeCleanupEvent);CLEANUP_ARENA(actions,action_count,SolMirRuntimeCleanupAction);CLEANUP_ARENA(transitions,transition_count,SolMirRuntimeCleanupTransition);CLEANUP_ARENA(supplemental_sites,supplemental_site_count,SolMirRuntimeCleanupSupplementalSite);CLEANUP_ARENA(drop_paths,drop_path_count,SolMirRuntimeCleanupDropPath);
#undef CLEANUP_ARENA
    return aliases_transitive(o,m);
}
static bool full(SolMirRuntimeHandlerAbiLimits x) { return x.max_frames&&x.max_marker_references&&x.max_cleanup_exits&&x.max_stack_depth&&x.max_test_work&&x.max_owned_bytes&&x.max_build_scratch_bytes&&x.max_build_work&&x.max_validation_scratch_bytes&&x.max_validation_work; }
static bool eqop(const SolMirMaterializedOperationKey*a,const SolMirMaterializedOperationKey*b,SolMirRuntimeHandlerAbiWorkMeter*m) { return tick(m)&&a->target_kind==b->target_kind&&tick(m)&&a->instance==b->instance&&tick(m)&&a->import==b->import&&tick(m)&&a->receiver==b->receiver&&tick(m)&&a->root==b->root&&tick(m)&&a->effects==b->effects; }
static bool transition_owns(const SolMirRuntimeCleanup*c,size_t action,size_t transition,SolMirRuntimeHandlerAbiWorkMeter*m) { if(!tick(m)||transition>=c->transition_count)return false;const SolMirRuntimeCleanupTransition*t=&c->transitions[transition];return tick(m)&&action>=t->actions.offset&&tick(m)&&action-t->actions.offset<t->actions.count; }
/* 12 owner fields and 10 final usage fields, then one iteration plus every
 * hash input for each authenticated record.  Keep this arithmetic paired
 * with seal() so construction can finalize build_work before live sealing. */
bool sol_mir_runtime_handler_abi_internal_seal_work(const SolMirRuntimeHandlerAbi*o,size_t*out) { size_t work=22,part;if(!o||!out||!mul(o->frame_count,28,&part)||!add(&work,part)||!mul(o->exit_marker_count,5,&part)||!add(&work,part)||!mul(o->cleanup_exit_count,4,&part)||!add(&work,part))return false;*out=work;return true; }
static bool reconstruct_build_work(const SolMirRuntimeHandlerAbi*o,size_t *out,SolMirRuntimeHandlerAbiWorkMeter*m) {
    const SolMirMaterialization*x=&o->conventions->concrete->materialization;const SolMirOperations*ops=&o->conventions->concrete->operations;size_t work=0;
    for(size_t i=0;i<ops->handler_count;i++) { if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        for(size_t q=0;q<x->instruction_count;q++)if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        for(size_t a=0;a<o->cleanup->action_count;a++)if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        for(size_t q=0;q<x->instruction_count;q++)if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        for(size_t pass=0;pass<2;pass++)for(size_t q=0;q<o->conventions->concrete->linkage.binding_count;q++)if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        for(size_t pass=0;pass<2;pass++)for(size_t q=0;q<o->conventions->signature_count;q++)if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        for(size_t q=0;q<x->plan->program->ir->file_count;q++)if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        for(size_t q=0;q<x->instruction_count;q++)if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;
        for(size_t a=0;a<o->cleanup->action_count;a++) { if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false;if(o->cleanup->actions[a].kind==SOL_MIR_RUNTIME_CLEANUP_ACTION_EXIT_HANDLER&&o->cleanup->actions[a].target==ops->handlers[i].handler)for(size_t t=0;t<o->cleanup->transition_count;t++)if(!tick(m)||!add(&work,1)||work>o->limits.max_build_work)return false; }
    }size_t seal_work=0;if(!tick(m)||!sol_mir_runtime_handler_abi_internal_seal_work(o,&seal_work)||!add(&work,seal_work)||work>o->limits.max_build_work)return false;*out=work;return true;
}
static bool source_for(const SolIr*ir,SolSpan span,SolMirRuntimeSource*out,SolMirRuntimeHandlerAbiWorkMeter*m) { bool found=false,unique=true;SolMirRuntimeSource source={0};if(!tick(m)||!ir||!out||span.start>span.end||span.end>ir->source_length)return false;for(size_t i=0;i<ir->file_count;i++){if(!tick(m))return false;const SolIrSourceFile*f=&ir->files[i];if(span.start>=f->aggregate_start&&span.end<=f->aggregate_end){if(found)unique=false;else source=(SolMirRuntimeSource){i,span.start-f->aggregate_start,span.end-f->aggregate_start};found=true;}}if(found&&unique)*out=source;return found&&unique; }
static bool linkage_for(const SolMirRuntimeConventions*c,SolMirMaterializedBindingId binding,SolMirLinkageTargetKind *kind,size_t *target,SolMirRuntimeHandlerAbiWorkMeter*m) { const SolMirLinkage*l=&c->concrete->linkage;size_t found=SOL_MIR_RUNTIME_NONE;for(size_t i=0;i<l->binding_count;i++){if(!tick(m))return false;if(l->bindings[i].binding==binding){if(!tick(m)||found!=SOL_MIR_RUNTIME_NONE)return false;found=i;}}if(!tick(m)||found==SOL_MIR_RUNTIME_NONE)return false;*kind=l->bindings[found].target_kind;*target=*kind==SOL_MIR_LINKAGE_TARGET_INTERNAL?l->bindings[found].internal:l->bindings[found].host;return true; }
static bool signature_for(const SolMirRuntimeConventions*c,SolMirLinkageTargetKind kind,size_t target,SolMirRuntimeSignatureId*out,SolMirRuntimeHandlerAbiWorkMeter*m) { size_t found=SOL_MIR_RUNTIME_NONE;for(size_t i=0;i<c->signature_count;i++){if(!tick(m))return false;const SolMirRuntimeSignature*s=&c->signatures[i];bool yes=kind==SOL_MIR_LINKAGE_TARGET_INTERNAL?s->origin==SOL_MIR_RUNTIME_SIGNATURE_INTERNAL&&s->internal==target:s->origin==SOL_MIR_RUNTIME_SIGNATURE_HOST&&s->host==target;if(yes){if(!tick(m)||found!=SOL_MIR_RUNTIME_NONE)return false;found=i;}}if(!tick(m)||found==SOL_MIR_RUNTIME_NONE)return false;*out=found;return true; }
static bool import_for(const SolMirRuntimeConventions*c,SolMirRuntimeSignatureId signature,SolMirRuntimeHandlerAbiWorkMeter*m) { if(!tick(m)||signature>=c->signature_count)return false;const SolMirRuntimeSignature*s=&c->signatures[signature];if(!tick(m)||s->origin!=SOL_MIR_RUNTIME_SIGNATURE_HOST)return false;size_t found=SOL_MIR_RUNTIME_NONE;for(size_t i=0;i<c->import_count;i++){if(!tick(m))return false;const SolMirRuntimeImport*x=&c->imports[i];if(x->kind==SOL_MIR_RUNTIME_IMPORT_HOST&&x->host==s->host){if(!tick(m)||found!=SOL_MIR_RUNTIME_NONE)return false;found=i;}}return tick(m)&&found!=SOL_MIR_RUNTIME_NONE; }
static uint64_t mix(uint64_t x,uint64_t v) { return (x^v)+UINT64_C(0x9e3779b97f4a7c15)+(x<<6)+(x>>2); }
/* The builder uses this with no meter to create the owner seal.  Validation
 * supplies its meter so every record iteration and every hash input that the
 * authentication check dereferences is charged before use. */
static bool seal(const SolMirRuntimeHandlerAbi*o,SolMirRuntimeHandlerAbiWorkMeter*m,uint64_t*out) { uint64_t x=UINT64_C(0x50332e352d68616);
#define MIX(v) do { if(m&&!tick(m))return false;x=mix(x,(uint64_t)(v)); } while(0)
    MIX((uintptr_t)o->conventions);MIX((uintptr_t)o->values);MIX((uintptr_t)o->cleanup);MIX((uintptr_t)o->host_abi);MIX((uintptr_t)o->frames);MIX(o->frame_count);MIX((uintptr_t)o->exit_markers);MIX(o->exit_marker_count);MIX((uintptr_t)o->cleanup_exits);MIX(o->cleanup_exit_count);MIX(o->limits.max_stack_depth);MIX(o->limits.max_test_work);MIX(o->usage.frames);MIX(o->usage.marker_references);MIX(o->usage.cleanup_exits);MIX(o->usage.stack_depth);MIX(o->usage.test_work);MIX(o->usage.owned_bytes);MIX(o->usage.build_scratch_bytes);MIX(o->usage.build_work);MIX(o->usage.validation_scratch_bytes);MIX(o->usage.validation_work);
    for(size_t i=0;i<o->frame_count;i++){if(m&&!tick(m))return false;const SolMirRuntimeHandlerFramePlan*f=&o->frames[i];MIX(f->handler);MIX(f->source.file);MIX(f->source.start);MIX(f->source.end);MIX(f->source_binding);MIX(f->source_operation.target_kind);MIX(f->source_operation.instance);MIX(f->source_operation.import);MIX(f->source_operation.receiver);MIX(f->source_operation.root);MIX(f->source_operation.effects);MIX(f->source_signature);MIX(f->root_match);MIX(f->authority_root);MIX(f->effects);MIX(f->provider_binding);MIX(f->provider_place);MIX(f->provider_recipe);MIX(f->provider_access);MIX(f->provider_internal);MIX(f->provider_signature);MIX(f->enter_marker);MIX(f->exit_markers.offset);MIX(f->exit_markers.count);MIX(f->cleanup_exits.offset);MIX(f->cleanup_exits.count);MIX(f->parent);}
    for(size_t i=0;i<o->exit_marker_count;i++){if(m&&!tick(m))return false;MIX(o->exit_markers[i].frame);MIX(o->exit_markers[i].instruction);MIX(o->exit_markers[i].image);MIX(o->exit_markers[i].block);}for(size_t i=0;i<o->cleanup_exit_count;i++){if(m&&!tick(m))return false;MIX(o->cleanup_exits[i].frame);MIX(o->cleanup_exits[i].action);MIX(o->cleanup_exits[i].transition);}
#undef MIX
    *out=x?x:1;return true;
}
bool sol_mir_runtime_handler_abi_internal_seal_metered(const SolMirRuntimeHandlerAbi*o,SolMirRuntimeHandlerAbiWorkMeter*m,uint64_t*out) { return seal(o,m,out); }

static SolMirRuntimeHandlerAbiBuildOutcome validate(const SolMirRuntimeHandlerAbi*o,SolDiagnostics*d,bool measuring,size_t*out) {
    if(!o||!full(o->limits)||!o->authentication||!o->conventions||!o->values||!o->cleanup||!o->host_abi||o->values->conventions!=o->conventions||o->cleanup->conventions!=o->conventions||o->cleanup->values!=o->values||o->host_abi->conventions!=o->conventions||o->host_abi->values!=o->values||o->host_abi->cleanup!=o->cleanup||o->frame_count!=o->frame_capacity||o->exit_marker_count!=o->exit_marker_capacity||o->cleanup_exit_count!=o->cleanup_exit_capacity){bad(d,"malformed runtime handler ABI owner");return SOL_MIR_RUNTIME_HANDLER_ABI_BUILD_INVALID_PREDECESSOR;}
    SolMirRuntimeHandlerAbiWorkMeter meter={o->limits.max_validation_work,0,false};
    size_t *seen=NULL;
#define CHECK(x,msg) do { bool checked;if(!tick(&meter))goto exhausted;checked=(x);if(meter.exhausted)goto exhausted;if(!checked){bad(d,msg);goto invalid;} } while(0)
    CHECK(range(o->frames,o->frame_count,sizeof *o->frames,&meter),"malformed runtime handler ABI owner");CHECK(range(o->exit_markers,o->exit_marker_count,sizeof *o->exit_markers,&meter),"malformed runtime handler ABI owner");CHECK(range(o->cleanup_exits,o->cleanup_exit_count,sizeof *o->cleanup_exits,&meter),"malformed runtime handler ABI owner");
    CHECK(!overlap(o->frames,o->frame_count,sizeof *o->frames,o->exit_markers,o->exit_marker_count,sizeof *o->exit_markers,&meter),"handler ABI arenas alias");CHECK(!overlap(o->frames,o->frame_count,sizeof *o->frames,o->cleanup_exits,o->cleanup_exit_count,sizeof *o->cleanup_exits,&meter),"handler ABI arenas alias");CHECK(!overlap(o->exit_markers,o->exit_marker_count,sizeof *o->exit_markers,o->cleanup_exits,o->cleanup_exit_count,sizeof *o->cleanup_exits,&meter),"handler ABI arenas alias");CHECK(!aliases(o,o,1,sizeof *o,&meter),"handler ABI arenas alias");CHECK(!aliases(o,o->conventions,1,sizeof *o->conventions,&meter),"handler ABI arenas alias");CHECK(!aliases(o,o->values,1,sizeof *o->values,&meter),"handler ABI arenas alias");CHECK(!aliases(o,o->cleanup,1,sizeof *o->cleanup,&meter),"handler ABI arenas alias");CHECK(!aliases(o,o->host_abi,1,sizeof *o->host_abi,&meter),"handler ABI arenas alias");
    CHECK(o->conventions->concrete,"invalid runtime handler ABI predecessor");CHECK(!aliases_predecessor(o,&meter),"handler ABI aliases predecessor arena");
    CHECK(!aliases(o,o->host_abi->capabilities,o->host_abi->capability_count,sizeof *o->host_abi->capabilities,&meter),"handler ABI aliases predecessor arena");CHECK(!aliases(o,o->host_abi->entry_roots,o->host_abi->entry_root_count,sizeof *o->host_abi->entry_roots,&meter),"handler ABI aliases predecessor arena");CHECK(!aliases(o,o->host_abi->operations,o->host_abi->operation_count,sizeof *o->host_abi->operations,&meter),"handler ABI aliases predecessor arena");CHECK(!aliases(o,o->host_abi->arguments,o->host_abi->argument_count,sizeof *o->host_abi->arguments,&meter),"handler ABI aliases predecessor arena");CHECK(!aliases(o,o->host_abi->formals,o->host_abi->formal_count,sizeof *o->host_abi->formals,&meter),"handler ABI aliases predecessor arena");CHECK(!aliases(o,o->host_abi->shapes,o->host_abi->shape_count,sizeof *o->host_abi->shapes,&meter),"handler ABI aliases predecessor arena");CHECK(!aliases(o,o->host_abi->shape_cases,o->host_abi->shape_case_count,sizeof *o->host_abi->shape_cases,&meter),"handler ABI aliases predecessor arena");CHECK(!aliases(o,o->host_abi->requirements,o->host_abi->requirement_count,sizeof *o->host_abi->requirements,&meter),"handler ABI aliases predecessor arena");
    CHECK(sol_mir_runtime_conventions_validate(o->conventions,d),"invalid runtime handler ABI predecessor");CHECK(sol_mir_runtime_values_validate(o->values,d),"invalid runtime handler ABI predecessor");CHECK(sol_mir_runtime_cleanup_validate(o->cleanup,d),"invalid runtime handler ABI predecessor");CHECK(sol_mir_runtime_host_abi_validate(o->host_abi,d),"invalid runtime handler ABI predecessor");
    const SolMirMaterialization*m=&o->conventions->concrete->materialization;const SolMirOperations*ops=&o->conventions->concrete->operations;size_t marker_total=0,cleanup_total=0,bytes=0,n,scratch=0,build_work=0;
    CHECK(mul(o->frame_count,sizeof *o->frames,&n)&&add(&bytes,n)&&mul(o->exit_marker_count,sizeof *o->exit_markers,&n)&&add(&bytes,n)&&mul(o->cleanup_exit_count,sizeof *o->cleanup_exits,&n)&&add(&bytes,n)&&mul(o->frame_count,sizeof(size_t),&scratch),"runtime handler ABI usage mismatch");CHECK(reconstruct_build_work(o,&build_work,&meter),"runtime handler ABI usage mismatch");CHECK(o->frame_count==ops->handler_count,"runtime handler ABI usage mismatch");CHECK(o->usage.frames==o->frame_count,"runtime handler ABI usage mismatch");CHECK(o->usage.marker_references==o->frame_count+o->exit_marker_count+o->cleanup_exit_count,"runtime handler ABI usage mismatch");CHECK(o->usage.cleanup_exits==o->cleanup_exit_count,"runtime handler ABI usage mismatch");CHECK(o->usage.stack_depth==o->frame_count,"runtime handler ABI usage mismatch");CHECK(o->usage.test_work==o->frame_count,"runtime handler ABI usage mismatch");CHECK(o->usage.owned_bytes==bytes,"runtime handler ABI usage mismatch");CHECK(o->usage.build_scratch_bytes==scratch,"runtime handler ABI usage mismatch");CHECK(o->usage.build_work==build_work,"runtime handler ABI usage mismatch");CHECK(o->usage.validation_scratch_bytes==scratch,"runtime handler ABI usage mismatch");CHECK(o->usage.frames<=o->limits.max_frames&&o->usage.marker_references<=o->limits.max_marker_references&&o->usage.cleanup_exits<=o->limits.max_cleanup_exits&&o->usage.stack_depth<=o->limits.max_stack_depth&&o->usage.test_work<=o->limits.max_test_work&&o->usage.owned_bytes<=o->limits.max_owned_bytes&&o->usage.build_scratch_bytes<=o->limits.max_build_scratch_bytes&&o->usage.build_work<=o->limits.max_build_work&&o->usage.validation_scratch_bytes<=o->limits.max_validation_scratch_bytes,"runtime handler ABI usage mismatch");
    if(o->frame_count){seen=sol_mir_runtime_handler_abi_internal_validation_scratch(o->frame_count,sizeof *seen);if(!seen){bad(d,"runtime handler ABI validation scratch allocation failed");return SOL_MIR_RUNTIME_HANDLER_ABI_BUILD_ALLOCATION_FAILED;}}
    for(size_t i=0;i<o->frame_count;i++) { CHECK(tick(&meter),"runtime handler ABI validation work exhausted");const SolMirRuntimeHandlerFramePlan*f=&o->frames[i];const SolMirOperationHandlerPlan*p=&ops->handlers[i];SolMirRuntimeSource source;SolMirLinkageTargetKind sk,pk;size_t st,pt;SolMirRuntimeSignatureId ss,ps;
        CHECK(f->handler==p->handler,"handler frame mismatch");CHECK(f->handler<m->handler_count,"handler frame mismatch");CHECK(!seen[f->handler]++,"handler frame mismatch");CHECK(f->parent==(p->frame_parent==SOL_MIR_OPERATION_NONE?SOL_MIR_RUNTIME_NONE:p->frame_parent),"handler frame mismatch");CHECK(f->parent==SOL_MIR_RUNTIME_NONE||f->parent<i,"handler frame mismatch");CHECK(f->root_match==SOL_MIR_OPERATION_ROOT_TOKEN_EQUAL,"handler frame mismatch");CHECK(f->source_binding==m->handlers[f->handler].source_binding,"handler frame mismatch");CHECK(f->provider_binding==m->handlers[f->handler].provider_binding,"handler frame mismatch");CHECK(eqop(&f->source_operation,&m->handlers[f->handler].operation,&meter),"handler frame mismatch");CHECK(f->authority_root==m->handlers[f->handler].authority,"handler frame mismatch");CHECK(f->effects==m->handlers[f->handler].operation.effects,"handler frame mismatch");CHECK(f->provider_place==m->handlers[f->handler].provider,"handler frame mismatch");CHECK(f->provider_place<m->place_count,"handler frame mismatch");CHECK(f->provider_recipe==m->places[f->provider_place].final_type,"handler frame mismatch");CHECK(f->provider_recipe<o->conventions->concrete->representation.recipe_count&&f->provider_recipe<o->values->recipe_operation_count&&f->provider_recipe<o->values->allocation_plan_count&&f->provider_recipe<o->values->copy_plan_count&&f->provider_recipe<o->values->ownership_plan_count,"handler frame mismatch");CHECK(o->values->recipe_operations[f->provider_recipe].recipe==f->provider_recipe&&o->values->allocation_plans[f->provider_recipe].recipe==f->provider_recipe&&o->values->copy_plans[f->provider_recipe].recipe==f->provider_recipe&&o->values->ownership_plans[f->provider_recipe].recipe==f->provider_recipe,"handler frame mismatch");CHECK(f->provider_access==p->provider_access,"handler frame mismatch");CHECK(f->enter_marker<m->instruction_count,"handler frame mismatch");CHECK(m->instructions[f->enter_marker].kind==SOL_MIR_INST_HANDLER_ENTER&&m->instructions[f->enter_marker].handler==f->handler,"handler frame mismatch");CHECK(source_for(o->conventions->concrete->program.ir,m->handlers[f->handler].span,&source,&meter),"handler frame mismatch");CHECK(!memcmp(&f->source,&source,sizeof source),"handler frame mismatch");CHECK(linkage_for(o->conventions,f->source_binding,&sk,&st,&meter)&&linkage_for(o->conventions,f->provider_binding,&pk,&pt,&meter),"handler linkage mismatch");CHECK(pk==SOL_MIR_LINKAGE_TARGET_INTERNAL&&f->provider_binding<m->binding_count&&m->bindings[f->provider_binding].target_kind==SOL_MIR_MATERIALIZED_TARGET_INSTANCE&&f->provider_internal==pt,"handler linkage mismatch");CHECK(signature_for(o->conventions,sk,st,&ss,&meter)&&signature_for(o->conventions,pk,pt,&ps,&meter),"handler signature mismatch");CHECK(f->source_signature==ss&&f->provider_signature==ps,"handler signature mismatch");
        CHECK((sk==SOL_MIR_LINKAGE_TARGET_HOST||sk==SOL_MIR_LINKAGE_TARGET_INTERNAL),"handler source target mismatch");if(sk==SOL_MIR_LINKAGE_TARGET_HOST){CHECK(import_for(o->conventions,f->source_signature,&meter),"handler import mismatch");CHECK(st<o->host_abi->operation_count&&o->host_abi->operations[st].host==st&&o->host_abi->operations[st].signature==f->source_signature&&o->host_abi->operations[st].effects==f->effects,"handler source target mismatch");}else CHECK(st<o->conventions->concrete->linkage.callable_count&&o->conventions->signatures[f->source_signature].origin==SOL_MIR_RUNTIME_SIGNATURE_INTERNAL,"handler source target mismatch");
        const SolMirRuntimeSignature*provider=&o->conventions->signatures[f->provider_signature];CHECK(provider->origin==SOL_MIR_RUNTIME_SIGNATURE_INTERNAL&&provider->effects<m->effect_row_count&&m->effect_rows[provider->effects].atoms.count==0,"provider is not pure internal");CHECK(f->exit_markers.offset<=o->exit_marker_count&&f->exit_markers.count<=o->exit_marker_count-f->exit_markers.offset,"handler exit marker range");for(size_t q=0;q<f->exit_markers.count;q++){CHECK(tick(&meter),"runtime handler ABI validation work exhausted");const SolMirRuntimeHandlerExitMarker*z=&o->exit_markers[f->exit_markers.offset+q];CHECK(z->frame==i&&z->instruction<m->instruction_count&&z->image==p->image&&m->instructions[z->instruction].kind==SOL_MIR_INST_HANDLER_EXIT&&m->instructions[z->instruction].handler==f->handler&&m->instructions[z->instruction].block==z->block,"handler exit marker mismatch");CHECK(add(&marker_total,1),"handler exit marker mismatch");}
        CHECK(f->cleanup_exits.offset<=o->cleanup_exit_count&&f->cleanup_exits.count<=o->cleanup_exit_count-f->cleanup_exits.offset,"handler cleanup-exit range");for(size_t q=0;q<f->cleanup_exits.count;q++){CHECK(tick(&meter),"runtime handler ABI validation work exhausted");const SolMirRuntimeHandlerCleanupExit*z=&o->cleanup_exits[f->cleanup_exits.offset+q];CHECK(z->frame==i&&z->action<o->cleanup->action_count&&o->cleanup->actions[z->action].kind==SOL_MIR_RUNTIME_CLEANUP_ACTION_EXIT_HANDLER&&o->cleanup->actions[z->action].target==f->handler&&transition_owns(o->cleanup,z->action,z->transition,&meter),"handler cleanup correlation mismatch");CHECK(add(&cleanup_total,1),"handler cleanup correlation mismatch");}
    }
    for(size_t i=0;i<m->instruction_count;i++){CHECK(tick(&meter),"runtime handler ABI validation work exhausted");if(m->instructions[i].kind==SOL_MIR_INST_HANDLER_EXIT){size_t found=0;for(size_t q=0;q<o->exit_marker_count;q++){CHECK(tick(&meter),"runtime handler ABI validation work exhausted");CHECK(add(&found,o->exit_markers[q].instruction==i),"handler exit marker coverage overflow");}CHECK(found==1,"handler exit marker coverage is not exact");}}
    for(size_t i=0;i<o->cleanup->action_count;i++){CHECK(tick(&meter),"runtime handler ABI validation work exhausted");if(o->cleanup->actions[i].kind==SOL_MIR_RUNTIME_CLEANUP_ACTION_EXIT_HANDLER){size_t found=0;for(size_t q=0;q<o->cleanup_exit_count;q++){CHECK(tick(&meter),"runtime handler ABI validation work exhausted");CHECK(add(&found,o->cleanup_exits[q].action==i),"handler cleanup-exit coverage overflow");}CHECK(found==1,"handler cleanup-exit coverage is not exact");}}
    uint64_t authentication=0;CHECK(marker_total==o->exit_marker_count&&cleanup_total==o->cleanup_exit_count,"runtime handler ABI authentication mismatch");CHECK(seal(o,&meter,&authentication),"runtime handler ABI authentication mismatch");CHECK(measuring||o->authentication==authentication,"runtime handler ABI authentication mismatch");CHECK(measuring||o->usage.validation_work==meter.used+2,"runtime handler ABI usage mismatch");CHECK(tick(&meter),"runtime handler ABI validation work exhausted");
    free(seen);if(out)*out=meter.used;return SOL_MIR_RUNTIME_HANDLER_ABI_BUILD_SUCCEEDED;
exhausted: free(seen);bad(d,"runtime handler ABI validation work exhausted");return SOL_MIR_RUNTIME_HANDLER_ABI_BUILD_RESOURCE_EXHAUSTED;
invalid: free(seen);return SOL_MIR_RUNTIME_HANDLER_ABI_BUILD_INVALID_PREDECESSOR;
#undef CHECK
}
SolMirRuntimeHandlerAbiBuildOutcome sol_mir_runtime_handler_abi_internal_validate(const SolMirRuntimeHandlerAbi*o,SolDiagnostics*d) { return validate(o,d,false,NULL); }
SolMirRuntimeHandlerAbiBuildOutcome sol_mir_runtime_handler_abi_internal_measure_validation_work(const SolMirRuntimeHandlerAbi*o,size_t*out,SolDiagnostics*d) { if(!out)return SOL_MIR_RUNTIME_HANDLER_ABI_BUILD_INVALID_ARGUMENT;*out=0;return validate(o,d,true,out); }
